### ISSUE TITLE
Issue with JobTracker freezing on later versions of gcs-connector

### ISSUE THREAD

**Issue by ap0** [GoogleCloudPlatform/bigdata-interop#3] opened 2015-02-27 20:38 UTC
Using Hadoop 1.2.1 with the latest GCS connector (as of this writing), we run into a condition after a job completes where the job tracker completely freezes for ~15 minutes (the web UI is inaccessible and applications cannot submit new jobs to the cluster, but the machine is still accessible).  This causes a bunch of headaches with job failures/etc.  This has happened on a couple clusters in GCE (one 128 node, one 16 node; namenode is sized appropriately).  It used to happen intermittently but now it's become very frequent.

I did a jstack dump when it was frozen which you can see here: https://gist.github.com/ap0/89c4fce43bfe177f15cd

The one that sticks out is this:
Thread 5369: (state = IN_NATIVE)
- java.net.SocketOutputStream.socketWrite0(java.io.FileDescriptor, byte[], int, int) @bci=0 (Interpreted frame)
- java.net.SocketOutputStream.socketWrite(byte[], int, int) @bci=52, line=113 (Interpreted frame)
- java.net.SocketOutputStream.write(byte[], int, int) @bci=4, line=159 (Interpreted frame)
- sun.security.ssl.OutputRecord.writeBuffer(java.io.OutputStream, byte[], int, int, int) @bci=5, line=377 (Interpreted frame)
- sun.security.ssl.OutputRecord.write(java.io.OutputStream, boolean, java.io.ByteArrayOutputStream) @bci=458, line=363 (Interpreted frame)
- sun.security.ssl.SSLSocketImpl.writeRecordInternal(sun.security.ssl.OutputRecord, boolean) @bci=62, line=830 (Interpreted frame)
- sun.security.ssl.SSLSocketImpl.writeRecord(sun.security.ssl.OutputRecord, boolean) @bci=302, line=801 (Interpreted frame)
- sun.security.ssl.AppOutputStream.write(byte[], int, int) @bci=161, line=122 (Interpreted frame)
- org.apache.http.impl.io.AbstractSessionOutputBuffer.write(byte[], int, int) @bci=34, line=128 (Interpreted frame)
  ...

It looks like it gets hung in this call.  My suspicion was that the connection dies during the transfer and there's no SO_TIMEOUT value set.  I tried changing this in the google-http-java-client by setting the SO_TIMEOUT value on SSL sockets (https://github.com/zulily/google-http-java-client/commit/380341e5119ecc03a1fbeb831f9806cd9844d182), which seemed promising but eventually did not work.  A colleague said they had issues with the job tracker locking up as well; they found the problem occurred after a job completed when it would write the log files to GCS; their fix was to just disable this log writing.

One thing that does work is to use the older version of gcs-connector which we have running on some other clusters (1.2.8).  This one does not seem to exhibit this behavior.  I think a regression occurred between then and now that is causing this, but I have been unable to track it down.

**Comment by dennishuo** [comment] 2015-02-27 20:57
Thanks for the report! My first suspicion would be that this could be related to the "directory modification timestamps of parent directories" feature, originally introduced in 1.2.9:

1.2.9 - 2014-09-18

  1. When directory contents are updated e.g., files or directories are added,
     removed, or renamed the GCS connector will now attempt to update a
     metadata property on the parent directory with a modification time. The
     modification time recorded will be used as the modification time in
     subsequent FileSystem#getStatus(...), FileSystem#listStatus and
     FileSystem#globStatus(...) calls and is the time as reported by
     the system clock of the system that made the modification.

Since the timestamps were really only important for some directories, we found it better to only turn on the feature for some paths:

1.3.0 - 2014-10-17

  1. Directory timestamp updating can now be controlled via user-settable
     properties "fs.gs.parent.timestamp.update.enable",
     "fs.gs.parent.timestamp.update.substrings.excludes". and
     "fs.gs.parent.timestamp.update.substrings.includes" in core-site.xml. By
     default, timestamp updating is enabled for the YARN done and intermediate
     done directories and excluded for everything else. Strings listed in
     includes take precedence over excludes.
  2. Directory timestamp updating will now occur on a background thread inside
     GoogleCloudStorageFileSystem.

You could try setting fs.gs.parent.timestamp.update.enable = false to see if it works around this issue while we try to dig into the root cause.

For reference, does this seem to get slower and slower the longer the jobtracker is running, or is it related to the size of the job? In your case, how long had the jobtracker been running, and approximately how many files did the slow jobs each process?

**Comment by medb** [comment] 2018-07-23 19:54
Closing as obsolete.
Please, reopen if it's still relevant.

**Closed by medb** 2018-07-23 19:54 UTC
