### ISSUE TITLE
Missing rows reading Google Cloud Storage gzipped through Spark

### ISSUE THREAD

**Issue by corradio** [GoogleCloudPlatform/bigdata-interop#66] opened 2017-09-07 07:53 UTC
Hi,

I have a Spark job from dataproc where I simply count the number of rows in a JSON newline-delimited file.
The number of lines is correct when I upload a plain text json.
The number of lines is incorrect (11 rows out of 576 in my example) when the json is gzipped first, and content-encoding: gzip is set as metadata in GCS.
I don't have this issue if I use gsutil to download the gzipped json and re-upload it (gsutil decompresses the file when downloaded, so the re-upload if effectively without compression)

Any clue?

Thanks

Olivier

**Comment by AngusDavis** [comment] 2017-09-07 16:19
Hi Olivier,

A few questions to help with tracking this down:
1) How large are both the compressed and uncompressed files?
2) Which APIs are being used to read the files?
3) If you use the hadoop command line tool to copy the file from GCS to a local file, does the local file have the correct content? (hadoop fs -copyToLocal gs://some-bucket/some-file ./some-file) 
4) As a test, what happens if you reset Content-Encoding to empty on the GCS object(s) and then retry? (gsutil setmeta -h "Content-Type: application/gzip" -h "Content-Encoding: " gs://bucket/file)

Thanks,
Angus

**Comment by corradio** [comment] 2017-09-08 08:14
Hi @AngusDavis ,

Thanks for your reply.
The raw json has 199 lines, and is 848K on my computer.
Once uploaded using `gsutil cp -Z`, the GCS web interface states 12.45 KB (and `gsutil` 12.5KiB). The file on GCS has the right Content-Type (application/json) and Content-Encoding (gzip) headers, and when downloaded using gsutil the file is correctly automatically decompressed.

I use python's `SparkContext` to read the files using `sc.textFile()`, running on a Dataproc cluster, submitted with `gcloud dataproc jobs submit pyspark`.
I count the number of lines using `sc.textFile('gs://some-bucket/compressed_file.json').count()`, and it returns 9 instead of 199.

Using `hadoop fs` I get the uncompressed file back with the proper size and number of lines.

Setting Content-Encoding to empty and Content-Type to application/gzip with gsutil yields a item count of 354 (because the content did not get decompressed).

However, giving the file the `.json.gz` extension instead of `.json`, together with application/gzip works because the Spark reader decompresses files with gzip when they end with `.gz`.

**Comment by AngusDavis** [comment] 2017-09-08 17:43
Thanks, @corradio,

Here's what I think is happening. In o.a.hadoop.mapreduce.lib.inputformat.FileFileInputFomat#getSplits, the file length, as reported by GCS, is used to compute start/end splits for this file. When content-encoding and transparent compression/decompression is used, GCS will report the size of the compressed blob, not the original size. As a result, getSplits is emitting a single split for this file from 0 to 12.4KB. 

When the LineRecordReader used by the TextInputFormat is given this split, it will read records until it passes 12.4K and then stop reading. 

When the file has a json.gz suffix and no content-encoding header, the LineRecordReader is correctly determining a codec and as the blob size reported by GCS is exactly the number of bytes the codec will need, everything works. 

I'm unfortunately not seeing a solution that would allow the use of transparent transcoding with Spark / Hadoop MR jobs at the GCS-Connector level. One option might be to provide your own FileInputFormat when reading data in Spark (sc.hadoopFile instead of sc.textFile). At a high level, this would look something like: 1) Create a subclass of LineRecordReader that alters initialize to use the gzip compression codec, and 2) Subclassing FileInputFormat to indicate the file is not splittable and provide your LineRecordReader subclass as a result of createRecordReader.

**Comment by corradio** [comment] 2017-09-08 18:25
I see. Shouldn't GCS report the size of the decompressed blob when transparent decompression is used? Can you point me to where in the GCS connector this happens?

**Comment by AngusDavis** [comment] 2017-09-08 22:15
Reading of GCS files all happens through the GoogleCloudStorageReadChannel. It has a bit of logic to disable its own internal length validations when the file encoding is gzip[1]. As for GCS reporting the exact size, AFAIK,  GCS doesn't actually have that information. When transparent transcoding is used, gsutil does the gzip on upload of the object. GCS just sees the compressed bytes and the header that indicates the object is gzipped. [2]

[1]: https://github.com/GoogleCloudPlatform/bigdata-interop/blob/b427d9157932385664229f81d0857cf13df071f5/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageReadChannel.java#L208
[2]: https://cloud.google.com/storage/docs/transcoding

**Comment by steveloughran** [comment] 2018-07-03 17:11
There's a foundational requirement in the Hadoop FS APIs, "I file is exactly how long as it says it is". That is, the following invariants hold

define measureLength(file) as the length of a file determined by opening it and counting how many bytes you get back

```java
long measureLength(Path path) {
long len = 0;
try (in = fs.open(path)) {
  while (in.read() >= 0)   len++;
}
return len;
}
```


```
getFieStatus(path).getLen() == measureLength(path)
listFiles(path)== measureLength(path)
forall (st in listStatus(path.getParent)) p.isFile() ==> p.getLen() == measureLength(path)
forall (st in listFiles(path.getParent), true ) p.isFile() ==> p.getLen() == measureLength(path)
```

This is not the first case that a store has returned a different amount [and it breaks things there too](https://issues.apache.org/jira/browse/HADOOP-13887). You aren't going to get spark to handle this unless the directory listing returns the actual length of the data you get when you read the files listed. That's how partitioning works.

**Comment by medb** [comment] 2018-07-04 03:00
@steveloughran thank you for clarification!

Does it mean that it's impossible to read `gzip` files in Hadoop FS API-compliant way because it's impossible to know `gzip` file size until it fully decompressed?

What will happen if read channel will return `-1` size, will it break something in Hadoop?

**Comment by medb** [comment] 2018-07-06 16:21
If I understand issue correctly, the current problem is that when GCS connector reads gzip files they are automatically decompressed by HTTP client library (Apache HTTP) and GCS connector could only return decompressed bytes that have greater size than size determined from GCS object metadata and returned by the `size()` method.

If above is the case then the only way to read as many bytes as `size()` method returns is to return compressed object bytes. Is this an expected behavior by Hadoop? I.e. does Hadoop expect that `FSInputStream` will automatically decompress gzip files, or not?

**Comment by medb** [comment] 2018-07-09 16:59
@steveloughran Will it break something in Hadoop if GCS `FSInputStream` will always return size equal to `Long.MAX_VALUE` for gzip-compressed files until end of the file is reached (underlying `InputStream` returned -1 during `read` call) and after that will return actual size of the file (i.e number of bytes read from underlying `InputStream`)?

**Comment by steveloughran** [comment] 2018-07-10 09:41
I've discussed having some getLength() call you could make on an open FSDataInputStream, so that we could handle postponing final length discovery until later. But not done it, nor tested to see what breaks.

A big issue is partitioning: Hive & Spark can split up a splittable file into parts to hand off to different workers, giving them (file, offset, range) details to tell them where to start to scan for the next entry, etc. I don't know how that would work in this world...you'd have to talk to the Hive/MR/Spark/Tez people to understand.

**Comment by medb** [comment] 2018-07-10 14:52
Thank you for explanation!

My guess is that splitting not so critical for gzip files because they are "unsplittable" and returning `Long.MAX_VALUE` in size method until file is fully read at lest prevents data loss, when not all records are read.

But I need to check the code to see what will happen if client will seek to the position after actual decompressed file size.

**Comment by medb** [comment] 2018-07-12 14:33
Tested with simple word count job in Spark and MR, the same problem still persist - need to dig deeper into it.

**Comment by steveloughran** [comment] 2018-07-12 16:30
This is a silly question: but do you really need server-side unzipping here? Do it on the client and you save on bandwidth. I know .gz isn't the most efficient to decompress, but nor is .csv. Best to use .csv.gz for ingress and then convert to something performant

**Comment by medb** [comment] 2018-07-12 16:53
It's even worse... it's not server-side unzipping, but Google GCS API client library unzipping.

GCS connector uses this library and unzipping is hard coded and could not be disabled - library automatically unzips everything that has `gzip` in `Content-Encoding` header.

We plan to switch to different client library, but it will take some time and it's not backward compatible, and current library is not actively developed, so it could be hard to add an option to disable this behavior.

**Comment by steveloughran** [comment] 2018-07-13 10:32
aah, that sucks. it means you cant handle .gz data sources

**Comment by medb** [comment] 2018-07-13 14:07
Looks like I identified root cause, when Spark reads files and splits them it takes file size not from `FSInputStream#size` method, but from `FileStatus` (separate GCS metadata request), which always returns size of compressed object.

Only way to fix this is to not decompress gzipped files on client. Will take a look what could be done here.

**Comment by medb** [comment] 2018-07-16 20:33
Thanks for explanation, I will try to hack HTTP API Client library to not decompress gzip files automatically - this is the only way to fix this issue.

**Comment by dennishuo** [comment] 2018-07-17 01:20
There is some misunderstanding in this thread.

"content-encoding" is *not* the same thing as storing content-type:gzip. Using gzip files with "content-encoding" flags set is explicitly not intended to be supported as a Hadoop filesystem input. The only reason gcsio has it is that there are some users who use the lower-layer library in a non-filesystem context.

In fact, naming a file ".gz" and then also setting "content-encoding: gzip" is almost certainly a bug in the use case, unless the user has actually doubly-gzipped the file for some reason. See https://www.quora.com/Whats-the-basic-difference-between-Content-Type-and-Content-Encoding-Header

The point of "content-encoding" headers is to be transparent to the user, i.e.  saving a file "foo.txt", and flipping on gzip content-encoding to save on storage and/or network, but users of any compliant client expect to see the raw text bytes, *not* the compressed bytes.

**Comment by dennishuo** [comment] 2018-07-17 01:40
Looks like the confusion was only in the part of the thread starting in 2018 though.

For the actual use case here, the correct thing to do is to store the files explicitly as .json.gz files, and not use "content-encoding" stuff; content-encoding is really predominantly a concept for things like browsers where clients are expected to hide the content-encoding details from the consumer.

So if you want compression, store explicitly compressed files where Spark gets accurate compressed-size info, and the Hadoop or Spark layer decompresses it.

Simply removing automatic decompression in the client library wouldn't really work generically either. In particular, with content-encoding, in theory any middleware may perform on-the-fly decompression for whatever reason it wants. This can be illustrated in this GCS case too, if you add an "accept-encoding: foo" header in the read request for an object that has "content-encoding: gzip" then the GCS backends actually will do the on-the-fly decoding first, and the client won't even have the opportunity to pass-through the compressed gzip bytes.

In general, "content-encoding" headers should be considered incompatible with Hadoop filesystem semantics.

**Comment by dennishuo** [comment] 2018-07-17 01:52
Here's a handy example of the semi-non-deterministic behavior allowed in the proxy layer for whether to serve up uncompressed bytes and strip the content-encoding header or to pass-through the encoded content: https://wiki.squid-cache.org/KnowledgeBase/VaryNotCaching

**Comment by medb** [comment] 2018-07-17 02:11
Closing as infeasible.

**Closed by medb** 2018-07-17 02:11 UTC
