### ISSUE TITLE
DynamicFileListRecordReader error

### ISSUE THREAD

**Issue by xardazz** [GoogleCloudPlatform/bigdata-interop#23] opened 2016-01-16 19:58 UTC
I'm experiencing issue with proper reader termination.
DynamicFileListRecordReader expects 0-record file to be present at the bucket path, but looks like it's not automatically created, so the reader goes into infinite loop.
 According to this
https://cloud.google.com/bigquery/exporting-data-from-bigquery 
this 0-record file is created only when using wildcard urls. But according to hadoop log single-url with no wildcards is used and that wait is unnecessary

My config for haddop job is

``` java
        BigQueryConfiguration.configureBigQueryInput(conf, "publicdata:samples.shakespeare");
        conf.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem");
        // tempoary path where to download data from BiqQuery tables
        conf.set(BigQueryConfiguration.TEMP_GCS_PATH_KEY, "gs://mybucket/mypath");
        conf.set(BigQueryConfiguration.PROJECT_ID_KEY, "myprojid");
        conf.set(GoogleHadoopFileSystemBase.GCS_PROJECT_ID_KEY, "myprojid");
```

So maybe remove that wait or make DynamicFileListRecordReader more flexible?

**Comment by rtshadow** [comment] 2016-04-22 16:30
Hi,
I've just ran into exactly same problem (my job was hanging on the export). I found this issue and as a workaround I tried to explicitly disable sharded export by doing:
`hadoopConf.setBoolean(BigQueryConfiguration.ENABLE_SHARDED_EXPORT_KEY, false);`
and to my surprise I got an error like this:
```
java.io.IOException: Cannot read and write in different locations: source: EU, destination: US
	at com.google.cloud.hadoop.io.bigquery.BigQueryUtils.waitForJobCompletion(BigQueryUtils.java:97)
	at com.google.cloud.hadoop.io.bigquery.UnshardedExportToCloudStorage.waitForUsableMapReduceInput(UnshardedExportToCloudStorage.java:87)
```

so what I did is that I fixed my input and outputs to be in the same location and then everything worked fine with sharded export enabled, no workaround needed.

This leads me to conclusion that this behaviour only occurs with cross-location exports. This is obviously bug in the connector, as it should throw an exception instead of hanging.

**Comment by AngusDavis** [comment] 2016-04-22 20:04
@rtshadow - thank you for bringing up that case. I've opened an internal bug to track that case (have the DynamicRecordReader monitor export status).

**Comment by jeffreyolchovy** [comment] 2017-08-22 08:01
Any update on this issue? I am experiencing similar behavior resulting in the `DynamicFileListRecordReader` instance hanging indefinitely. 

If I try to export an unpartitioned table with a few records and `BigQueryConfiguration.ENABLE_SHARDED_EXPORT_KEY` is set to `true`, the 0 record file is never created and the record reader continues to wait for another resource.

**Comment by juliankeppel** [comment] 2017-12-07 06:43
Hi use the spotify spark-bigquery connector (https://github.com/spotify/spark-bigquery) in version 0.2.2 which uses bigdata-interop in version `0.10.2-haddop2`. First I load meta data from <dataset>.__TABLES__ and then the actual data. Since some days I face the same problem mentioned here. The job hangs at `DynamicFileListRecordReader` when I want to load the (pretty small) meta table from BigQuery. Loading the actual "data" tables works as before.

Since I haven't change any lib versions or code in my application, it seems that there has something changed in BigQuery or Cloud Storage itself?

**Comment by pmkc** [comment] 2018-04-02 20:33
I think the issue is that BigQuery does not create the 0 record file when using a single wildcard, which is why there is [MIN_SHARDS_FOR_SHARDED_EXPORT = 2](../blob/ea2bb01bf2d81296cb6d71a64d35589516331f8a/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/ShardedExportToCloudStorage.java#L61).

However mapreduce.job.maps=1 (like in local mode) used to overrule that before [ea2bb01](../commit/ea2bb01).

Closing since this should the minimum should now be enforced, and BigQuery should always create the 0 byte files.

**Closed by pmkc** 2018-04-02 20:33 UTC
